datafruits/streampusher-api

app/controllers/api/listeners_controller.rb
app/models/user/roles.rb
config/routes.rb

related PR in datafruits/datafruits
https://github.com/datafruits/datafruits/pull/520

add listeners_controller

---

.github/workflows/ci.yml
spec/services/dj_signup_spec.rb

resolves https://github.com/datafruits/streampusher-api/issues/21

try to fix CI

---

Gemfile
Gemfile.lock
app/workers/discord_notifier.rb
config/initializers/notifications.rb

use discord for activity notifications

---

app/models/user.rb
db/migrate/20201109111436_add_style_to_users.rb

related https://github.com/datafruits/datafruits/issues/522

add user styles

---

script/setup
script/test

This fixes some issues during setup.

Use compose cluster that `script/app` expects.

---

app/controllers/current_user_controller.rb
app/models/ability.rb
config/routes.rb

new API endpoint needed for https://github.com/datafruits/datafruits/pull/623

add update current user action

---

config/deploy/shared/log_rotation.erb
config/schedule.rb

add logrotate to scheduler

---

app/services/radio_booter.rb
config/secrets.yml

This allows the radio to use a licensed version of stereotool.

pass stereo tool key to radio container

---

app/controllers/scheduled_shows_controller.rb
app/models/scheduled_show.rb
app/serializers/scheduled_show_serializer.rb
app/views/scheduled_shows/_form.html.erb
app/views/scheduled_shows/show.html.erb
db/migrate/20210528014036_add_guest_to_scheduled_shows.rb
db/schema.rb
spec/models/scheduled_show_spec.rb

resolves: https://github.com/datafruits/streampusher-api/issues/90

add guest fields to scheduled_show

---

app/controllers/application_controller.rb

I usually end up changing the `current_radio` method to use the first radio in dev anyway, so let's just make that the default in dev.

try to make dev life easier @current_radio

---

app/models/host_application.rb
app/services/dj_signup.rb
spec/models/host_application_spec.rb

This lets users be converted from listener to dj role successfully.

let user signup if they have a dj role

---

config/deploy/shared/log_rotation.erb
docker-compose.yml

* mount the log dir in container
* add splat to rotate logs in subdirectory

rotate icecast logs

---

app/controllers/process_recordings_controller.rb
app/controllers/recordings_controller.rb
app/serializers/recording_serializer.rb

to work with streampusher beta

add json API for recordings

---

app/controllers/current_user_controller.rb

add bio to allowed params for updating profile on datafruits user

---

app/controllers/api/fruit_summons_controller.rb
app/models/fruit_summon.rb
app/models/fruit_summon_entity.rb
app/models/fruit_ticket_transaction.rb
app/models/user.rb
app/serializers/fruit_summon_serializer.rb
app/serializers/user_serializer.rb
app/services/fruit_summon_transaction.rb
app/workers/supporters_monthly_fruit_tickets_worker.rb
config/routes.rb
db/migrate/20221112063956_fruit_ticket_balances.rb
db/migrate/20221112175850_create_fruit_ticket_transactions.rb
db/migrate/20221127182813_create_fruit_summons.rb
db/migrate/20221127193523_create_fruit_summon_entities.rb
db/schema.rb
spec/models/fruit_ticket_transaction_spec.rb
spec/models/link_spec.rb
spec/services/fruit_summon_transaction_spec.rb

fruit ticket balances/transaction types

---

app/models/fruit_ticket_transaction.rb
app/workers/payout_fruit_ticket_track_plays_worker.rb
config/sidekiq.yml
spec/workers/payout_fruit_ticket_track_plays_worker_spec.rb

This worker should run every 24 hours in a cronjob.

archive playback fruit ticket payouts worker

---

config/routes.rb

resolves https://github.com/datafruits/datafruits/issues/1028

allow dots in url for /djs API

---

app/models/wiki_page.rb
spec/models/wiki_page_spec.rb

add a callback to set the slug to nil, this ensures a new slug is generated

make sure wiki page slugs update on save

---

config/routes.rb

Reverts datafruits/streampusher-api#217

Revert "allow question marks in forum thread ids"

---

app/models/user/roles.rb
app/workers/badge_awards_worker.rb

This needs some stricter validation or type checking....

fix watermelon badge typo

---

docker-compose-dev.yml

Trying to run the app from the same docker-compose-dev file should be a good enough test I think.

Default docker dev networking for ubuntu

---

.github/workflows/ci.yml
app/lib/redis_connection.rb
config/initializers/geocoder.rb
config/initializers/redis.rb
config/initializers/sidekiq.rb
spec/fixtures/vcr_cassettes/create_container.yml
spec/fixtures/vcr_cassettes/set_env.yml
spec/fixtures/vcr_cassettes/start_container.yml

Includes CI setup and test fixes.

CI and test fixes

---

app/services/streaming_exp_award.rb

Maybe some db constraints could help as well.

make sure streaming_exp_award is not given twice

---

app/services/streaming_exp_award.rb
app/workers/streaming_exp_award_worker.rb
spec/services/streaming_exp_award_spec.rb

resolves https://github.com/datafruits/streampusher-api/issues/257

award xp to all show hosts

---

app/services/process_recording.rb
app/services/streaming_exp_award.rb
app/workers/streaming_exp_award_worker.rb
spec/services/streaming_exp_award_spec.rb

try to find show from filename in process_recording before calling

---

app/models/notification.rb
app/models/user/roles.rb
app/workers/badge_awards_worker.rb

we don't need no stinkin badges

---

app/controllers/radios_controller.rb
config/routes.rb

https://github.com/datafruits/streampusher-frontend/pull/197

add controller for queuing current show's playlist

---

app/models/scheduled_show.rb
app/services/process_recording.rb
app/workers/process_recording_worker.rb
spec/models/scheduled_show_spec.rb

- add processed recordings to shows
- add spec for recording scheduled_show_spec

add processed recordings to show

---

app/models/show_series.rb
spec/models/show_series_spec.rb

- fix time warp bug
- fix time warp bug

fix time warp bug

---

app/controllers/api/my_shows_controller.rb
config/initializers/notifications.rb

track show series one off creation

---

app/controllers/api/my_shows_controller.rb
app/serializers/error_serializer.rb

- more logging for error
- log update error

fix error params

---

app/models/user/roles.rb
app/workers/supporters_monthly_fruit_tickets_worker.rb
spec/models/user_spec.rb

update supporter payout worker for new roles

---

app/models/scheduled_show.rb
app/models/show_series.rb
app/models/track.rb
app/models/user.rb

Reverts datafruits/streampusher-api#353

Revert "append timestamp to attachment filenames"

---

app/models/notification.rb
app/models/user.rb

also send image url to show in chat

send url in user update notifications

---

app/controllers/api/my_shows_controller.rb

can't remember why I had it the other way before

fix guest shows create

---

app/controllers/api/my_shows_controller.rb

- Revert "fix guest shows create"
- fix time params

fix guest shows create again

---

app/services/metadata_publisher.rb
app/services/metadata_update.rb

also .strip to remove excess whitespace

raise if blank passed to metadata updaters

---

app/services/payout_fruit_ticket_track_plays.rb

maybe i should save for archiving tho?

delete track plays after payout

---

app/models/track.rb

this seems to be causing some corruption in the mp3 files

dont assign track image

---

app/controllers/api/archives_controller.rb
app/controllers/api/djs_controller.rb

copied off the archives controller for the DJs controller. trying to add pagination for the frontend and saw that param wasn't being referenced here yet

Add page to djs

---

app/controllers/api/archives_controller.rb

add preloading for scheduled shows query

archives-controller-perf

---

app/serializers/shrimpo_serializer.rb

- **create shrimpo entries zip file**
- **debug**
- **fix worker scope**
- **forgot to commit worker**
- **entries zip shrimpo serializer**

shrimpo zip file

---

app/controllers/api/my_shows_controller.rb

- **fix logic in guest show create**
- **remove old commented code**

fix create guest show

---

app/models/shrimpo.rb
app/models/shrimpo_vote.rb
app/models/shrimpo_voting_category.rb
app/serializers/shrimpo_serializer.rb
app/serializers/shrimpo_voting_category_serializer.rb
db/migrate/20240721171936_add_shrimpo_type_to_shrimpos.rb
db/schema.rb

- **add shrimpo type to shrimpos**
- **add shrimpo_type column to shrimpos**

shrimpo voting categories

---

app/controllers/scheduled_shows_controller.rb
app/services/live_notification.rb
app/services/next_track.rb

store current show / current archive in redis
TODO need to clear current show after disconnect/scheduled show switches
over

current show api

---

Gemfile
Gemfile.lock
app/models/notification.rb
app/models/patreon_pledge.rb

also try to set the role/badge when its created

get tier name from patreon pledge

---

app/lib/giphy_text_animator.rb
app/models/notification.rb
app/models/scheduled_show.rb
app/services/liquidsoap_requests.rb
app/services/live_notification.rb
app/services/schedule_monitor.rb
spec/fixtures/vcr_cassettes/PatreonWebhookHandler_saves_the_pledge_to_the_db_and_sends_a_notification.yml
spec/services/patreon_webhook_handler_spec.rb

- **fix syncing metadata from liquidsoap**
- **fix current show metadata**
- **doops**
- **add giphy text gif to patreon pledge notif**

giphy text gif patreon pledge

---

app/controllers/api/djs/episodes_controller.rb

use fast serializer in djs/episodes_controller

---

app/controllers/publish_metadata_controller.rb
app/services/canonical_metadata_sync.rb

fix typo in canonical_metadata_sync

fix args passed in publish_metadata_controller
